# CQ2: Which Philosophy courses are online in Fall 2026?

PREFIX umphil: <https://firdaus-gupte.github.io/umass-philosophy/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?CourseCode ?CourseTitle 
WHERE {
  ?offering umphil:isOfferedInTerm umphil:Fall2026 ;
            umphil:isOfferingOf ?Course .
  
  ?Course a umphil:PhilosophyCourse ;
          rdfs:label ?CourseCode ;
          umphil:hasCourseTitle ?CourseTitle .
  ?offering a umphil:OnlineCourseOffering .
 
}
ORDER BY ?CourseCode